### ISSUE TITLE
[Remoto] Desenvolvedor Pleno/Sênior Node.js

### ISSUE THREAD

**Issue by williamkoller** [NestBR/vagas#2]
> 100% Remota

## Requisitos

Especialidade em Node.js.
Preferencialmente que tenham conhecimento em desenvolvimento em Express ou Nest.
Experiência com Postgres é diferencial.

## Local

Não informada

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
Quem tiver interesse por favor enviar o currículo para: Ingrid.prudencio@5aattiva.com.br

**Comment by cwrlys** [comment]
A vaga ainda está aberta?
